name: Deploy to Netlify

on:
  push:
    branches:
      - main  # ajuste se seu branch principal tiver outro nome

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: ./build
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }} #Colocado la no github essa env
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          deploy-message: "Deploy automático via GitHub Actions"
